app:
  jwt_secret_key: test-secret
  access_token_expiry: 2h
  refresh_token_expiry: 168h

server:
  host: localhost
  port: 8080

database:
  user: postgres
  password: 123
  host: localhost
  port: 5432
  dbname: chipsi
  sslMode: false
